version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    working_dir: /app/src
    volumes:
      - ./backend/src:/app/src
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
